services:
  db:
    image: postgres:15-alpine
    container_name: cloud_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cloud_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app/src
      - ./client:/app/client
      - ./migrations:/app/migrations
      - ./run.sh:/app/run.sh
      - ./requirements.txt:/app/requirements.txt
    x-develop:
      watch:
        - action: sync+restart
          paths: ["src"]
        - action: sync+restart
          paths: ["client"]
        - action: rebuild+restart
          paths: ["run.sh", "requirements.txt"]

volumes:
  db_data:

